# Generated by Django 6.0.6 on 2026-07-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20210624_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerotelefonico',
            name='valor_mensual',
            field=models.FloatField(default=0.0),
        ),
    ]
